import Foundation
import Combine

enum InterfaceLanguage: String, Codable, CaseIterable {
    case system, english, chinese
    var label: String { switch self { case .system: return L("跟随系统"); case .english: return "English"; case .chinese: return "中文" } }
    func resolved(preferredLanguages: [String] = Locale.preferredLanguages) -> InterfaceLanguage {
        guard self == .system else { return self }
        // Only the first system language determines the fallback; unsupported languages use English.
        return preferredLanguages.first?.lowercased().replacingOccurrences(of: "_", with: "-").split(separator: "-").first == "zh" ? .chinese : .english
    }
}
final class Localization: ObservableObject {
    static let shared = Localization()
    @Published var selection = InterfaceLanguage.system
    var language: InterfaceLanguage { selection.resolved() }
    static let translations: [String: String] = [
        "滚动到最新": "Scroll to Latest",
        "配置文件版本不受支持": "Unsupported configuration file version",
        "无法保存本机 JSON 配置": "Unable to save local JSON configuration",
        "本机配置目录无效": "Invalid local configuration directory",
        "本机配置文件无效": "Invalid local configuration file",
        "本机 JSON 配置无法读取，请检查文件格式；原文件未覆盖": "Unable to read local JSON configuration. Check its format; the original file has not been overwritten.",
        "仅终端": "Terminal Only",
        "主机、用户名或端口无效": "Invalid host, username or port",
        "私钥文件留在本机；加密私钥的口令由终端提示或 SSH Agent 处理": "Private keys stay on this Mac. Use the terminal prompt or SSH Agent for encrypted key passphrases.",
        "跟随系统": "Follow System",
        "浅色": "Light",
        "深色": "Dark",
        "设置": "Settings",
        "设置…": "Settings…",
        "新建本地终端": "New Local Terminal",
        "新建聊天": "New Chat",
        "新聊天": "New Chat",
        "新文件夹": "New Folder",
        "关闭当前终端": "Close Current Terminal",
        "终端": "Terminal",
        "终端历史与搜索": "Terminal History & Search",
        "导出会话": "Export Session",
        "无终端": "No Terminal",
        "AI 正在回复": "AI is responding",
        "AI 未配置": "AI not configured",
        "删除聊天？": "Delete chat?",
        "取消": "Cancel",
        "删除": "Delete",
        "好": "OK",
        "SSH 书签": "SSH Bookmarks",
        "管理文件夹": "Manage Folders",
        "添加主机书签后点击连接。SSH 密码及主机指纹确认会在真实终端中显示。": "Add a bookmark to connect. SSH authentication and host verification use OpenSSH.",
        "聊天": "Chats",
        "重命名": "Rename",
        "打开本地终端": "Open Local Terminal",
        "清空当前聊天": "Clear Current Chat",
        "锁定 AI 上下文；命令仍发送到当前可见终端": "Pin AI context; commands still go to the visible terminal",
        "终端与 AI，一起工作。": "Your terminal and AI, together.",
        "可以问普通问题，也可以分析当前终端。选中终端文本后右键 Ask AI，即可带入上下文。": "Ask a general question or analyze your terminal. Select terminal text and right-click Ask AI to include context.",
        "在设置中 Continue with ChatGPT 即可连接。OpenAI API、Ollama 与 LM Studio 位于 Advanced / Other Providers。": "Connect with Continue with ChatGPT in Settings. OpenAI API, Ollama and LM Studio are under Advanced / Other Providers.",
        "停止": "Stop",
        "发送": "Send",
        "你": "You",
        "已附终端上下文": "Terminal context included",
        "需谨慎确认": "Review carefully",
        "低风险": "LOW",
        "复制": "Copy",
        "填入": "Insert",
        "执行…": "Run…",
        "潜在危险命令": "Potentially Dangerous Command",
        "确认执行": "Confirm & Run",
        "如果终端正在 vim、密码提示或其他交互程序中，请先取消并退出该程序。": "If the terminal is in vim, a password prompt or another interactive program, cancel and exit it first.",
        "连接你的 AI，保留完整终端体验。": "Connect your AI. Keep your full terminal experience.",
        "模型名称": "Model Name",
        "API Key（JSON 配置）": "API Key (JSON Configuration)",
        "OpenAI API 使用独立 API 密钥与计费。ChatGPT 连接保存在上方。": "OpenAI API uses a separate API key and billing. Your ChatGPT connection is managed above.",
        "请先启动服务，并填写该服务实际提供的模型名称。": "Start the service first and enter a model name it actually provides.",
        "Shell 路径": "Shell Path",
        "界面主题": "Appearance",
        "界面语言": "Language",
        "系统语言为中文时使用中文，其他语言使用英语。保存后立即生效。": "Follow System uses Chinese for Chinese system languages and English otherwise. Changes apply when saved.",
        "界面布局": "Layout",
        "显示书签栏": "Show Bookmarks Sidebar",
        "显示聊天栏": "Show Chat Panel",
        "恢复默认布局": "Restore Default Layout",
        "主题应用于整个界面、弹窗、聊天输入框和终端。": "Appearance applies to the entire interface, dialogs, chat input and terminal.",
        "保存聊天到本机": "Save Chats Locally",
        "发送前自动脱敏": "Redact Before Sending",
        "自动替换消息、历史聊天及终端上下文中的常见敏感字段，不弹出确认框。": "Automatically replace common sensitive fields in messages, chat history and terminal context without a confirmation dialog.",
        "按原文发送消息、历史聊天及终端上下文；其中的密码、Token 或私钥也会发送给当前 AI Provider。": "Send messages, chat history and terminal context unchanged, including any passwords, tokens or private keys, to the selected AI provider.",
        "终端回滚仅保存在当前进程。发送问题时，所选上下文会提交给当前 AI Provider。": "Terminal scrollback stays in this process. Selected context is sent to the current AI provider with your question.",
        "保存": "Save",
        "首选": "Preferred",
        "使用 ChatGPT": "Use ChatGPT",
        "已连接": "Connected",
        "ChatGPT plan（套餐名称未返回）": "ChatGPT plan (plan name unavailable)",
        "（待验证）": " (unverified)",
        "刷新模型": "Refresh Models",
        "账户": "Account",
        "待验证账户": "Unverified Account",
        "连接其他 ChatGPT 账户": "Connect Another ChatGPT Account",
        "Using ChatGPT plan · 合资格请求使用你授权的套餐或可用额度。": "Using ChatGPT plan · Eligible requests use your authorized plan or available allowance.",
        "读取账户…": "Loading account…",
        "取消连接": "Cancel Connection",
        "在系统浏览器完成登录和套餐授权，无需 API Key。成功验证身份后显示账户与模型。": "Sign in and authorize plan usage in your system browser. No API key needed. Your account and models appear after verification.",
        "TermGPT 中合资格的 AI 请求会使用你授权的 ChatGPT 套餐或可用额度。你可以在 ChatGPT Settings → Usage 管理访问和用量。": "Eligible TermGPT AI requests use your authorized ChatGPT plan or available allowance. Manage access and usage in ChatGPT Settings → Usage.",
        "连接": "Connect",
        "编辑 / 重命名": "Edit / Rename",
        "移动到文件夹": "Move to Folder",
        "未分类": "Unfiled",
        "删除书签": "Delete Bookmark",
        "管理书签文件夹": "Manage Bookmark Folders",
        "新建文件夹": "New Folder",
        "文件夹名称": "Folder Name",
        "删除文件夹后，其中的书签移到未分类，不删除书签。修改名称后点击保存。": "Deleting a folder moves its bookmarks to Unfiled without deleting them. Click Save to apply changes.",
        "重命名聊天": "Rename Chat",
        "聊天名称": "Chat Name",
        "新增 SSH 书签": "Add SSH Bookmark",
        "编辑 SSH 书签": "Edit SSH Bookmark",
        "名称": "Name",
        "例如：开发服务器": "e.g. Development Server",
        "主机 / SSH config 别名": "Host / SSH Config Alias",
        "主机名或 config 别名": "Hostname or SSH config alias",
        "端口": "Port",
        "用户名": "Username",
        "留空使用 SSH config": "Leave blank to use SSH config",
        "可选": "Optional",
        "文件夹": "Folder",
        "登录方式": "Authentication",
        "密码": "Password",
        "私钥": "Private Key",
        "保存到本机 JSON 配置，不使用钥匙串": "Stored in local JSON configuration; Keychain is not used",
        "SSH 登录密码": "SSH Password",
        "私钥路径": "Private Key Path",
        "选择…": "Choose…",
        "备注": "Notes",
        "采用系统 OpenSSH，兼容 ~/.ssh/config、SSH Agent 和 Known Hosts。保存的密码仅通过 SSH 认证组件使用；首次连接仍需确认主机指纹。": "Uses system OpenSSH with ~/.ssh/config, SSH Agent and Known Hosts. Saved passwords are read only by the SSH authentication helper; first connections still require host verification.",
        "搜索文本": "Search Text",
        "刷新": "Refresh",
        "关闭": "Close",
        "Enter 发送 · ⌥Enter 换行": "Enter to send · ⌥Enter for a new line",
        "聊天输入，Enter 发送，Option Enter 换行": "Chat input. Enter to send, Option Enter for a new line",
        "准备中": "Preparing",
        "SSH 进程运行中": "SSH process running",
        "本地 Shell": "Local Shell",
        "未知": "unknown",
        "已关联所选文本，点击发送后提交给 AI": "Selected text attached; click Send to submit it to AI",
        "填入仅接受单行且不含控制字符的命令。多行代码请复制后手动检查。": "Insert accepts only a single line without control characters. Copy and review multiline code manually.",
        "当前终端已退出": "The current terminal has exited",
        "自动执行仅支持单行命令；多行脚本请手动审查。": "Automatic execution supports single-line commands only. Review multiline scripts manually.",
        "目标终端已退出": "The target terminal has exited",
        "私钥文件不可读，请检查路径与权限": "Private key file is unreadable. Check its path and permissions.",
        "缺少 SSH 密码登录组件，请使用完整安装包": "SSH password helper is missing. Use the complete application package.",
        "无法创建 PTY 进程": "Unable to create PTY process",
        "请选择私钥文件": "Choose a private key file",
        "请输入要保存的 SSH 密码": "Enter the SSH password to save",
        "请输入有效的 API Base URL，例如 https://api.openai.com/v1": "Enter a valid API base URL, such as https://api.openai.com/v1",
        "远程 API 必须使用 HTTPS；HTTP 仅用于本机模型": "Remote APIs require HTTPS. HTTP is supported only for local models.",
        "请在设置中填写模型名称": "Enter a model name in Settings",
        "模型在流式响应中报告错误": "The model reported an error in its streaming response",
        "登录令牌编码无效": "Invalid login token encoding",
        "无法创建安全登录请求": "Unable to create a secure login request",
        "登录回调无效": "Invalid login callback",
        "登录回调参数重复": "Duplicate login callback parameters",
        "登录 state 校验失败": "Login state verification failed",
        "ChatGPT 授权未完成或已取消": "ChatGPT authorization was incomplete or canceled",
        "登录回调缺少授权码": "Login callback has no authorization code",
        "返回的账户注册不匹配": "Returned account registration does not match",
        "ChatGPT 尚未完成应用注册": "ChatGPT app registration is incomplete",
        "ChatGPT 身份校验失败，请重新连接": "ChatGPT identity verification failed. Reconnect your account.",
        "登录令牌尚未生效": "Login token is not yet valid",
        "无法启动本机登录回调": "Unable to start the local login callback",
        "正在等待浏览器授权…": "Waiting for browser authorization…",
        "无法打开系统浏览器": "Unable to open the system browser",
        "登录未返回 ID token": "Login did not return an ID token",
        "返回的 ChatGPT 身份与已选账户不匹配": "Returned ChatGPT identity does not match the selected account",
        "账户已验证，但尚未授权 ChatGPT plan usage。请重新连接并允许套餐使用。": "Account verified, but ChatGPT plan usage is not authorized. Reconnect and allow plan usage.",
        "连接已取消": "Connection canceled",
        "ChatGPT 令牌交换失败，请重新连接": "ChatGPT token exchange failed. Reconnect your account.",
        "ChatGPT 凭据响应不完整": "Incomplete ChatGPT credentials response",
        "无法确认 OpenAI 登录服务": "Unable to verify the OpenAI login service",
        "登录服务返回不可信地址": "Login service returned an untrusted URL",
        "无法获取登录签名密钥": "Unable to fetch login signing keys",
        "请在设置中 Continue with ChatGPT": "Choose Continue with ChatGPT in Settings",
        "ChatGPT 登录已过期，请重新连接": "ChatGPT login has expired. Reconnect your account.",
        "ChatGPT 套餐权限已失效，请重新连接": "ChatGPT plan access has expired. Reconnect your account.",
        "无法获取 ChatGPT 可用模型，请刷新或重新连接": "Unable to fetch ChatGPT models. Refresh or reconnect your account.",
        "当前账户未返回可选模型": "No models were returned for this account",
        "尚未取得当前账户的可用模型，请在设置中刷新模型": "Models are not available yet. Refresh models in Settings.",
        "ChatGPT 使用额度已到限制，请在 Settings → Usage 查看并管理用量": "ChatGPT usage limit reached. Review usage in Settings → Usage.",
        "ChatGPT 返回未完成的响应，请重新尝试": "ChatGPT returned an incomplete response. Try again.",
        "ChatGPT 响应连接中断，回复尚未完成": "ChatGPT connection interrupted before the response finished",
        "已断开连接": "Disconnected",
        "本机已断开；远端撤销未确认，可在 ChatGPT Settings 中移除应用访问。": "Disconnected locally. Remote revocation is unconfirmed; remove app access in ChatGPT Settings if needed.",
        "登录签名密钥不匹配": "Login signing key does not match",
        "登录签名格式无效": "Invalid login signature format",
        "不支持或不可信的登录签名算法": "Unsupported or untrusted login signature algorithm",
        "ChatGPT 身份签名校验失败": "ChatGPT identity signature verification failed",
        "登录身份内容无效": "Invalid login identity contents",
        "高级 / 其他供应商": "Advanced / Other Providers",
        "AI 供应商": "AI Provider",
        "终端与隐私": "Terminal & Privacy",
        "套餐": "Plan",
        "模型": "Model",
        "自动": "Auto",
        "断开连接": "Disconnect",
        "管理用量": "Manage usage",
        "状态": "Status",
        "连接中…": "Connecting…",
        "未连接": "Not connected",
        "继续使用 ChatGPT": "Continue with ChatGPT",
        "你正在使用 ChatGPT 套餐": "You're using your ChatGPT plan",
        "知道了": "Got it",
        "使用 ChatGPT 套餐": "Using ChatGPT plan",
        "ChatGPT · 未连接": "ChatGPT · Not connected",
        "选中文本": "Selected text",
        "最近 50 行": "Last 50 lines",
        "最近 200 行": "Last 200 lines",
        "整个会话": "Entire session",
        "关闭上下文": "Off",
        "向 AI 提问": "Ask AI",
        "解释": "Explain",
        "修复": "Fix",
        "生成命令": "Generate command",
        "AI 聊天": "AI Chat",
        "API 基础地址": "API Base URL",
        "SSH 配置 / Agent": "SSH config / Agent",
        "上下文：%@ · 默认仅建议命令": "Context: %@ · Commands are suggestions by default",
        "删除“%@”及其本地消息记录。": "Delete “%@” and its locally stored messages.",
        "目标终端：%@": "Target terminal: %@",
        "字体大小 %@": "Font size %@",
        "终端历史 · %@": "Terminal History · %@",
        "聊天菜单：%@": "Chat menu: %@",
        "书签菜单：%@": "Bookmark menu: %@",
        "已退出：%@": "Exited: %@",
        "本地保存失败：%@": "Local save failed: %@",
        "Shell 不可执行：%@": "Shell is not executable: %@",
        "ChatGPT 请求失败（HTTP %@），请检查登录或套餐授权": "ChatGPT request failed (HTTP %@). Check login and plan authorization.",
        "配置清除失败，请重试：%@": "Configuration deletion failed. Try again: %@",
        "已填入 %@，未按 Enter；执行前请检查当前输入行及程序": "Inserted into %@ without Enter. Review the input line and current program before running.",
        "已向 %@ 发送命令": "Command sent to %@",
        "%@：请分析选中的终端文本。": "%@: Please analyze the selected terminal text.",
        "AI 接口返回 HTTP %@，请检查地址、模型及密钥": "AI API returned HTTP %@. Check endpoint, model and key."
    ]
    private static let reverse = Dictionary(translations.sorted { $0.key < $1.key }.map { ($0.value, $0.key) }, uniquingKeysWith: { first, _ in first })
    static func text(_ key: String, language: InterfaceLanguage, preferredLanguages: [String] = Locale.preferredLanguages) -> String {
        let chinese = language.resolved(preferredLanguages: preferredLanguages) == .chinese
        if let english = translations[key] { return chinese ? key : english }
        if let chineseText = reverse[key] { return chinese ? chineseText : key }
        // Translate app-generated interpolated status/error messages without modifying their arguments.
        for (zh, en) in translations where zh.contains("%@") {
            let source = chinese ? en : zh, target = chinese ? zh : en
            let parts = source.components(separatedBy: "%@")
            let pattern = "^" + parts.map(NSRegularExpression.escapedPattern(for:)).joined(separator: "(.*?)") + "$"
            guard let regex = try? NSRegularExpression(pattern: pattern, options: [.dotMatchesLineSeparators]),
                  let match = regex.firstMatch(in: key, range: NSRange(key.startIndex..., in: key)) else { continue }
            let values = (1..<match.numberOfRanges).compactMap { Range(match.range(at: $0), in: key).map { String(key[$0]) } }
            return interpolate(target, values)
        }
        return key
    }
    static func interpolate(_ format: String, _ arguments: [String]) -> String {
        let parts = format.components(separatedBy: "%@")
        return parts.enumerated().map { index, part in part + (index < parts.count - 1 ? (index < arguments.count ? arguments[index] : "%@") : "") }.joined()
    }
}
func L(_ key: String, _ arguments: String...) -> String {
    Localization.interpolate(Localization.text(key, language: Localization.shared.selection), arguments)
}
